import Link from "next/link";

type Props = {
  params: {
    id: string;
  };
};

export const generateMetadata = ({ params }: Props) => {
  return {
    title: "안녕하세요 어바웃 페이지입니다",
    description: "Generated by create next app",
  };
};

const AboutPage = () => {
  return (
    <>
      About Page 입니다!<Link href={"/about2"}>About2로 가기</Link>
    </>
  );
};

export default AboutPage;
